// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SocialPostgresValidator is an autogenerated mock type for the SocialPostgresValidator type
type SocialPostgresValidator struct {
	mock.Mock
}

// SocialMustExist provides a mock function with given fields:
func (_m *SocialPostgresValidator) SocialMustExist() {
	_m.Called()
}
